# Generated by Django 4.2.7 on 2026-01-22 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#0078d4', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемая'),
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='voting_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Окончание голосования'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='voting_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало голосования'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='voting_category',
        ),
        migrations.AlterModelTable(
            name='nomination',
            table='voting_nomination',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='voting_vote',
        ),
    ]
