# Generated by Django 5.2.14 on 2026-05-25 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_historicalvote_historicalnomination_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'is_featured'], name='voting_cate_is_acti_e017ce_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='voting_cate_slug_56263b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['priority'], name='voting_cate_priorit_2989c8_idx'),
        ),
        migrations.AddIndex(
            model_name='nomination',
            index=models.Index(fields=['category', 'is_active'], name='voting_nomi_categor_9a4876_idx'),
        ),
        migrations.AddIndex(
            model_name='nomination',
            index=models.Index(fields=['voting_start', 'voting_end'], name='voting_nomi_voting__65aded_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user', 'nomination'], name='voting_vote_user_id_7b2592_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['rating'], name='voting_vote_rating_dc34cb_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['created_at'], name='voting_vote_created_f40b96_idx'),
        ),
    ]
