# Generated by Django 5.2.14 on 2026-05-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, verbose_name='Slug'),
        ),
    ]
